# **Numpy**

: 파이썬에서 선형대수 기반의 배열 연산을 빠르게 수행하도록 지원하는 라이브러리
# 1. 넘파이 ndarray 개요
- ndarray : 넘파이의 기반 데이터 타입
- 넘파이 array() 함수는 다양한 인자를 입력받아 ndarray로 변환



In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
#1차원 array로 3개의 데이터를 가지고 있음

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
#2차원 array로 2*3=6개의 데이터를 가지고 있음

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)
#3개의 데이터를 가지고 있지만 2차원 데이터

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


# 2. ndarray의 데이터 타입
- ndarray내의 데이터값은 숫자 값, 문자열 값, 불 값 등 모두 가능
- 숫자형의 경우 int형, unsigned int형, float형, complex형 제공
- ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능

In [ ]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)
#astype()매서드를 이용한 ndarray 내 데이터값의 타입 변경
#메모리 절약 가능

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# 3. ndarray를 편리하게 생성하기 - arange, zeros, ones
- 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용

In [ ]:
#arange()는 array를 range()로 표현하는 것
#0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
#zeros()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
#ones()는 함수 인자로 튜프 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환

zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# 4. ndarray의 차원과 크기를 변경하는 reshape()
- reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#reshape()는 지정된 사이즈로 변경이 불가능하면 오류 발생
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
#-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환

array1 = np.arange(10) #1차원 ndarray로 0~9까지의 데이터를 가지고 있음
print(array1)
array2 = array1.reshape(-1, 5) #고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1) #10개의 1차원 데이터와 호환되는 5X2의 2차원 ndarray로 변환
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
#호환될 수 없는 형태

array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [ ]:
#reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이며 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장

array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# 5. 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
- 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정
- 슬라이싱: 연속된 인덱스상의 ndarray를 추출하는 방식. ':' 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환
- 팬시 인덱싱: 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
- 불린 인덱싱: True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환
- 단일 데이터값 추출을 제외한 나머지는 모두 ndarray 타입

In [ ]:
#단일 값 추출

#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop=10)
print('array1:', array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [ ]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
#단일 인덱스를 이용한 ndarray 내의 데이터값 수정

array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
#다차원 ndarray에서의 단일 값 추출

#앞 코드의 1차원 ndarray를 2차원의 3X3 ndarray로 변환한 후 [row, col]을 이용해 2차원 ndarray에서 데이터 추출
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

#axis 0은 로우 방향의 축을 의미
#axis 1은 칼럼 방향의 축을 의미
#ndarray에서는 로우와 칼럼 대신에 axis 0, axis 1이 정확한 표현

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [ ]:
#슬라이싱

array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#':'기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
#':'기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
#':'기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

array1 = np. arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 2차원 ndarray에서의 슬라이싱

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


In [ ]:
#array2d[0]과 같이 2차원에서 뒤에 오는 인덱스를 없애면 로우 축 (axis 0)의 첫 번째 로우 ndarray를 반환
#3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray를 반환

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [ ]:
#팬시 인덱싱

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0,1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0,1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


In [ ]:
#불린 인덱싱
#조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식

array1d = np.arange(start=1, stop=10)
#[ ]안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
array1d > 5

#조건으로 반환된 ndarray 객체를 인덱싱을 지정하는 []내에 입력하면 False 값은 무시하고 True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

#동일한 데이터 세트 반환

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 ;', array4)

일반 인덱스로 필터링 결과 ; [6 7 8 9]


# 6. 행렬의 정렬 - sort()와 argsort()
- np.sort() : 넘파이에서 sort()를 호출하는 방식
- ndarray.sort() : 행렬 자체에서 sort()를 호출하는 방식
- np.sort()는 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환, ndarray.sort()는 원 행렬 자체를 정렬한 형태로 변환

In [ ]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
#np.sort(), ndarray.sort() 모두 기본적으로 오름차순 정렬
#내림차순 정렬은 [::-1] 적용

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
#행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향 또는 칼럼 방향으로 정렬 가능

array2d = np.array([[8, 12], [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [ ]:
#정렬된 행렬의 인덱스를 반환하기
#원본 행렬이 정렬되었을 때 기존 원보 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬으 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬으 인덱스: [1 0 3 2]


In [ ]:
#내림차순 정렬 시

org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 7. 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
- 행렬 내적 (행렬 곱) : np.dot()을 이용해 계산

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


- 전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 정치 행렬이라 함. transpose() 이용

In [ ]:
A = np.array([[1, 2], [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
