#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np

a = np.random.random((5,3))
b = np.random.random((3,2))
c = np.dot(a,b)

print(c)

[[0.0735174  0.70920852]
 [0.17810324 0.32521144]
 [0.36643254 0.74681937]
 [0.72304372 1.41682897]
 [0.45025442 0.87990075]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [22]:
Z = np.arange(11)

Z[(3 < Z) & (Z <= 8)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9
10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

nan
0
[-9.22337204e+18]

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [24]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

common = np.intersect1d(Z1, Z2)

print(common)

[4 6 7 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

print(np.sqrt(-1))

print(np.emath.sqrt(-1))

print(np.sqrt(-1) == np.emath.sqrt(-1))

#False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
A = np.arange(1, 10, dtype = float)
B = np.arange(1, 10, dtype = float)

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

print(A)

[ -1.  -4.  -9. -16. -25. -36. -49. -64. -81.]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
A = np.random.uniform(0, 10, 10)
print(A - A%1)

B = np.random.uniform(0, 10, 10)
print(B // 1)

[1. 7. 4. 6. 8. 7. 3. 6. 4. 9.]
[2. 8. 3. 3. 9. 7. 4. 4. 5. 1.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
A = np.arange(5)
B = np.array([A]*5)

print(B)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)

Z.sort()

print(Z)

[0.04830617 0.15429487 0.23178025 0.44172195 0.54227719 0.56847196
 0.58018219 0.70082337 0.80239403 0.86961688]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A)
print(B)

print(np.array_equal(A,B))

[0 1 0 1 1]
[0 1 0 0 1]
False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [25]:
Z = np.random.random((10,2))

X = Z[:,0]
Y = Z[:,1]

R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)

print(R)
print(T)

[0.56681435 0.49200522 0.79677414 0.2859511  0.73629009 1.02812741
 0.56243585 0.69829904 0.31702778 0.36480182]
[0.90306234 1.20360605 1.4209463  0.40312247 0.21611069 0.39236074
 0.1261265  0.14186449 0.09618596 0.96551488]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z = np.random.random(10)

Z[Z.argmax()] = 0

print(Z)

[0.1296659  0.4259062  0.69528512 0.66314075 0.26856631 0.
 0.52022054 0.10377379 0.37008155 0.47875239]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [26]:
Z = np.arange(100)
v = np.random.uniform(0,100)

i = (np.abs(Z - v)).argmin()

print(Z[i])

90


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [27]:
Z = np.arange(9).reshape(3, 3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [20]:
n = 5
p = 4

Z = np.zeros((n, n))

np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)

print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [28]:
Z = np.random.randint(0,10,(3,3))

print(Z)
print(Z[Z[:,0].argsort()])

[[3 8 0]
 [0 3 9]
 [6 9 0]]
[[0 3 9]
 [3 8 0]
 [6 9 0]]


In [29]:
print(Z)
print(Z[Z[:,1].argsort()])

[[3 8 0]
 [0 3 9]
 [6 9 0]]
[[0 3 9]
 [3 8 0]
 [6 9 0]]


In [30]:
print(Z)
print(Z[Z[:,2].argsort()])

[[3 8 0]
 [0 3 9]
 [6 9 0]]
[[3 8 0]
 [6 9 0]
 [0 3 9]]
